services:
  web:
    build: 
      context: .
      target: prod
    container_name: cookery-corner-web
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./assets:/var/www/html/assets
    networks:
      - shared-network
networks:
  shared-network:
    external: true